version: "3.8"

services:

  app:
    container_name: app
    build: .
    command: bash -c "uvicorn main:app --host 0.0.0.0 --port 8080"
    volumes:
      - ./src/:/app
    ports:
      - 8080:8080
    links:
      - redis
      - celery_worker
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}
      - CELERY_RESULT_BACKEND=${CELERY_RESULT_BACKEND}
    restart: always

  redis:
    container_name: redis
    image: redis:7.2.4-alpine
    ports:
      - "6379:6379"

  celery_worker:
    container_name: celery_worker
    build: .
    command: celery -A celery_worker.celery_app worker --loglevel=info
    volumes:
      - ./src/:/app
    environment:
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}
      - CELERY_RESULT_BACKEND=${CELERY_RESULT_BACKEND}
      - REDIS_HOST=${REDIS_HOST}
    links:
      - redis
    depends_on:
      - redis

  flower:
    container_name: flower
    build: .
    command: celery -A celery_worker.celery_app flower --port=5555
    ports:
      - 5556:5555
    volumes:
      - ./src/:/app
    environment:
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}
      - CELERY_RESULT_BACKEND=${CELERY_RESULT_BACKEND}
      - REDIS_HOST=${REDIS_HOST}
    depends_on:
      - app
      - redis
      - celery_worker
